version: '3.7'

services:
  discord:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./app/:/app
    extra_hosts:
      - host.docker.internal:host-gateway

  next:
    build: 
      context: ./next-archive
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./next-archive/:/next-archive
    extra_hosts:
      - host.docker.internal:host-gateway

  db:
    image: mariadb:10
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - backend
    restart: always

networks:
  backend:


